### ISSUE TITLE
Fehlermeldung Pre-existing zen_get_tax_locations function detected.

### ISSUE THREAD

**Issue by Anton2024tf** [zencartpro/157-modul-edit-orders#1]
Ich habe das Grundsystem neu installiert, die Module COWOA, dpu, Gutschein Editor, Urlaubsmeldung und Zahlungsart nur für bestimmte Kunden. Und nun das Modul Edit Orders. Jetzt erscheint nach Klick auf den entsprechenden Button eine weiße Seite und in den Logfiles die Fehlermeldung: Pre-existing zen_get_tax_locations function detected. in /sTomp-xMn-Pinch/includes/functions/extra_functions/edit_orders_functions.php on line 302.

**Comment by webchills** [comment]
Wenn Du bereits Zen Cart 1.5.7g verwendest, dann ist die alte Edit Orders Version 4.6.2 dafür nicht geeignet. Ende März wird Edit Orders 4.7.1 released, das Repository ist bereits auf diese Version aktualisiert. Bitte entferne 4.6.2 und lade Dir die aktuelle Version über den Code Button herunter. Nur die ist für 1.5.7g und die Ende März erscheinende 1.5.7h geeignet.

**Comment by Anton2024tf** [comment]
Danke! Aber was heißt über den Code-Button runterladen. Wenn ich auf den Button "Download (.zip)" klicke, erhalte ich die Version 4.6.2

**Comment by webchills** [comment]
Nicht über Releases, sondern über den grünen Code Button. Dann erhältst Du ein zip namens 157-modul-edit-orders-main.zip und das ist die kommende Version 4.7.1
![repository](https://github.com/zencartpro/157-modul-edit-orders/assets/1009695/a5b476a1-b595-4def-b8e2-f5e2efccf099)

**Comment by Anton2024tf** [comment]
Ah, ok. Es war mir nicht klar, dass ich das direkt hier bei github runterlade. Danke Dir!

**Comment by Anton2024tf** [comment]
Danke nochmal! Das funktioniert super. Allerdings kommt in den Logfiles, selbst wenn ich nicht Edit Orders verwende folgende Warnung. Was bedeutet das und woran könnte das liegen?

Request URI: /MyAdmin/index.php?cmd=display_logs, IP address: [...], Language id not set
#0 /MyAdmin/includes/extra_datafiles/edit_orders_defines.php(5): zen_debug_error_handler()
#1 /MyAdmin/includes/init_includes/init_file_db_names.php(44): require('...')
#2 /MyAdmin/includes/application_bootstrap.php(158): require('...')
#3 /MyAdminh/index.php(12): require_once('...')
--> PHP Warning: Constant FILENAME_EDIT_ORDERS already defined in /MyAdmin/includes/extra_datafiles/edit_orders_defines.php on line 5.

**Comment by webchills** [comment]
1.5.7g German requires Edit Orders 4.7.1 which will be released soon
