### ISSUE TITLE
Zencart 1.5.7 Edit Orders Issue

### ISSUE THREAD

**Issue by kleinefrau** [zencartpro/157-modul-edit-orders#2]
[02-Apr-2024 10:35:55 Europe/Berlin] Request URI: /xxx/admin/index.php?cmd=display_logs, IP address: 127.0.0.1, Language id 43
#0 local\admin\includes\classes\observers\EditOrdersAdminObserver.php(22): zen_debug_error_handler()
#1 local\includes\autoload_func.php(50): EditOrdersAdminObserver->__construct()
#2 local\admin\includes\application_top.php(44): require('local...')
#3 locali\admin\display_logs.php(35): require('local..')
#4 local\admin\index.php(18): require('Clocal...')
--> PHP Deprecated: Creation of dynamic property EditOrdersAdminObserver::$is157OrLaterZenCart is deprecated in local\admin\includes\classes\observers\EditOrdersAdminObserver.php on line 22.

**Comment by webchills** [comment]
So ein deprecated log ist völlig harmlos.
ABER: Anscheinend wird hier noch 1.5.7, 1.5.7e oder 1.5.7f verwendet, sonst würde das gesamte Edit Orders Modul 4.6.2 nicht funktionieren.
Edit Orders 4.6.2 ist veraltet und für neuere 1.5.7 Versionen (1.5.7g oder 1.5.7h) nicht geeignet.
Edit Orders Version 4.7.1 wird in den nächsten Tagen released. Bitte Shop auf 1.5.7h aktualisieren und in 1.5.7h dann Edit Orders 4.7.1 verwenden.
Solange noch 1.5.7, 1.5.7e oder 1.5.7f mit Edit Orders 4.6.2 verwendet wird, dieses harmlose Log löschen.

**Comment by kleinefrau** [comment]
Danke für die rasche Antwort. Ist wirklich ein sehr nützliches Modul.
Verwende 1.5.7h und habe ihr Modul von: https://www.zen-cart-pro.at/themen/module-157/ runtergeladen.
Die neue Zen Cart Version läuft nun auf PHP-Version: 8.2.12

**Comment by webchills** [comment]
will be fixed in 4.7.1
