### ISSUE TITLE
Missing changing Possibilities

### ISSUE THREAD

**Issue by BlubberBlaster** [zencartpro/157-modul-edit-orders#3]
Hello and great thanks for your incredible addon.
In your new version I can't
change Products (title)
Model

Before I could add a comment (This possibilty is gone)

Unit Price (Net)
Unit Price (Gross)

In commitment with customer I could alter the Price. Now I can't.

Will there be change in future.

Regards Anton Kmostak

**Comment by webchills** [comment]
Zen Cart 1.5.7h
Edit Orders 4.7.1
Everything you describe (products name, products_model, products_price net, products_price gross)  is of course changeable, so no idea what you mean.
If you can' t change the net price set configuration > edit orders > product price calculation method to manual.
If you can't change the other things there is something completely wrong with your installation.
